import { Resume } from './types';

export const resumesMock: Resume[] = [
  {
    id: '1',
    created_at: '2024-08-13T00:00:00.000Z',
    name: 'React Frontend Разработчик',
    description: 'Опытный фронтенд-разработчик с фокусом на React и TypeScript.',
    skills: [
      'HTML5',
      'CSS3',
      'JavaScript (ES6+)',
      'TypeScript',
      'React',
      'Vue.js',
      'Angular',
      'jQuery',
    ],
    work_schedule: [1, 2],
    employment_type: [1],
    preferred_income: 120000,
    education: [
      {
        id: 'edu-1',
        name: 'Фронтенд-разработка',
        organization: 'Hexlet',
        type: 'course',
        year: '2023',
      },
      {
        id: 'edu-2',
        name: 'Прикладная информатика',
        organization: 'МГУ',
        type: 'university',
        year: '2020',
      },
    ],
    experience: [
      {
        id: 'exp-1',
        position: 'Frontend Developer',
        organization: 'Tech Solutions',
        start_date: '2022-05-01',
        end_date: '2024-04-01',
        description: 'Разработка SPA приложений на React и TypeScript.',
        city: 1,
      },
      {
        id: 'exp-2',
        position: 'Junior Developer',
        organization: 'Startup XYZ',
        start_date: '2020-06-01',
        end_date: '2022-04-30',
        description: 'Поддержка и развитие внутренних сервисов компании.',
        city: 2,
      },
    ],
    link: 'https://github.com/ivanivanov',
  },
  {
    id: '2',
    created_at: '2024-09-10T00:00:00.000Z',
    name: 'Backend Разработчик Node.js',
    description: 'Специалист по созданию высоконагруженных API на Node.js и TypeScript.',
    skills: [
      'Node.js',
      'TypeScript',
      'NestJS',
      'PostgreSQL',
      'MongoDB',
      'Redis',
      'Docker',
      'Kubernetes',
    ],
    work_schedule: [1],
    employment_type: [1, 2],
    preferred_income: 150000,
    education: [
      {
        id: 'edu-3',
        name: 'Разработка веб-приложений',
        organization: 'Яндекс Практикум',
        type: 'course',
        year: '2022',
      },
      {
        id: 'edu-4',
        name: 'Информационные системы и технологии',
        organization: 'СПбГУ',
        type: 'university',
        year: '2021',
      },
    ],
    experience: [
      {
        id: 'exp-3',
        position: 'Backend Developer',
        organization: 'CloudTech',
        start_date: '2022-07-01',
        end_date: '2024-08-01',
        description: 'Разработка микросервисной архитектуры для корпоративных систем.',
        city: 3,
      },
      {
        id: 'exp-4',
        position: 'Software Engineer',
        organization: 'Innovative Systems',
        start_date: '2020-09-01',
        end_date: '2022-06-30',
        description: 'Работа над внутренними инструментами автоматизации.',
        city: 4,
      },
    ],
    link: 'https://github.com/petropetrov',
  },
];
