import { Vacancy } from './types';

export const vacanciesMock: Vacancy[] = [
  {
    id: '1',
    title: 'Frontend Developer (React)',
    description: 'Ищем опытного фронтенд-разработчика для работы над SPA на React.',
    skills: [
      { label: 'React' },
      { label: 'TypeScript' },
      { label: 'Redux' },
      { label: 'HTML/CSS' },
    ],
    price_from: 1500,
    price_to: 2500,
    experience: { label: 'от 2 лет' },
    city: { label: 'Москва' },
  },
  {
    id: '2',
    title: 'Backend Developer (Node.js)',
    description: 'Разработка и поддержка серверной логики на Node.js в крупном проекте.',
    skills: [
      { label: 'Node.js' },
      { label: 'Express' },
      { label: 'MongoDB' },
      { label: 'TypeScript' },
    ],
    price_from: 1800,
    price_to: 3000,
    experience: { label: 'от 3 лет' },
    city: { label: 'Санкт-Петербург' },
  },
  {
    id: '3',
    title: 'Fullstack Developer (React + Node.js)',
    description: 'Полный цикл разработки веб-приложений: фронтенд и бэкенд.',
    skills: [
      { label: 'React' },
      { label: 'Node.js' },
      { label: 'TypeScript' },
      { label: 'PostgreSQL' },
    ],
    price_from: 2000,
    price_to: 3500,
    experience: { label: 'от 4 лет' },
    city: { label: 'Казань' },
  },
  {
    id: '4',
    title: 'DevOps Engineer',
    description: 'Автоматизация процессов деплоя и настройка CI/CD пайплайнов.',
    skills: [
      { label: 'Docker' },
      { label: 'Kubernetes' },
      { label: 'AWS' },
      { label: 'Terraform' },
    ],
    price_from: 2200,
    price_to: 3700,
    experience: { label: 'от 3 лет' },
    city: { label: 'Екатеринбург' },
  },
  {
    id: '5',
    title: 'Mobile Developer (React Native)',
    description: 'Разработка мобильных приложений для iOS и Android на React Native.',
    skills: [
      { label: 'React Native' },
      { label: 'TypeScript' },
      { label: 'REST API' },
      { label: 'Redux' },
    ],
    price_from: 1600,
    price_to: 2700,
    experience: { label: 'от 2 лет' },
    city: { label: 'Новосибирск' },
  },
];
